<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    
    <!-- Deterministic build settings -->
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    
    <!-- Common package metadata -->
    <Authors>CodeOOf</Authors>
    <Company>SysDocs</Company>
    <Product>SysDocs</Product>
    <Copyright>Copyright © 2025 CodeOOf</Copyright>
    <PackageProjectUrl>https://github.com/CodeOOf/SysDocs</PackageProjectUrl>
    <RepositoryUrl>https://github.com/CodeOOf/SysDocs</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>0.1.0-alpha</Version>
  </PropertyGroup>
</Project>
