using System.Reflection;
using System.Text;
using SysDocs.Tests.Attributes;
using Xunit;

namespace SysDocs.Tests.Tools;

/// <summary>
/// Generates a traceability report showing requirement-to-test mapping
/// Run: dotnet run --project tests/SysDocs.Tests -- --report
/// </summary>
public class TraceabilityReportGenerator
{
    public static string GenerateReport()
    {
        var assembly = Assembly.GetExecutingAssembly();
        var testMethods = assembly.GetTypes()
            .SelectMany(t => t.GetMethods())
            .Where(m => m.GetCustomAttribute<FactAttribute>() != null || 
                       m.GetCustomAttribute<TheoryAttribute>() != null)
            .ToList();

        var requirementMap = new Dictionary<string, List<TestInfo>>();

        foreach (var method in testMethods)
        {
            var reqAttrs = method.GetCustomAttributes<RequirementTestAttribute>();
            var categoryAttrs = method.GetCustomAttributes<TestCategoryAttribute>();
            var factAttr = method.GetCustomAttribute<FactAttribute>() ?? 
                          method.GetCustomAttribute<TheoryAttribute>() as FactAttribute;

            // Get the first category or default
            var category = categoryAttrs.FirstOrDefault()?.Category ?? "Unknown";

            foreach (var reqAttr in reqAttrs)
            {
                if (!requirementMap.ContainsKey(reqAttr.RequirementId))
                {
                    requirementMap[reqAttr.RequirementId] = new List<TestInfo>();
                }

                requirementMap[reqAttr.RequirementId].Add(new TestInfo
                {
                    TestName = method.Name,
                    FullName = $"{method.DeclaringType?.FullName}.{method.Name}",
                    TestType = reqAttr.TestType,
                    Category = category,
                    Description = reqAttr.Description,
                    IsSkipped = !string.IsNullOrEmpty(factAttr?.Skip)
                });
            }
        }

        return BuildMarkdownReport(requirementMap, testMethods.Count);
    }

    private static string BuildMarkdownReport(Dictionary<string, List<TestInfo>> requirementMap, int totalTests)
    {
        var sb = new StringBuilder();
        
        sb.AppendLine("# Test Traceability Report");
        sb.AppendLine();
        sb.AppendLine("> ⚠️ **AUTO-GENERATED FILE - DO NOT MANUALLY EDIT**  ");
        sb.AppendLine("> This file is automatically generated by: `dotnet run --project tests/SysDocs.Tests -- --traceability`  ");
        sb.AppendLine("> Any manual changes will be overwritten on the next generation.  ");
        sb.AppendLine("> For V&V strategy and procedures, see [../project/VERIFICATION_VALIDATION.md](../project/VERIFICATION_VALIDATION.md) and [../docs/VV_SETUP_SUMMARY.md](../docs/VV_SETUP_SUMMARY.md)");
        sb.AppendLine();
        sb.AppendLine($"**Generated:** {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"**Total Tests:** {totalTests}");
        sb.AppendLine($"**Requirements Covered:** {requirementMap.Count}");
        sb.AppendLine();

        // Summary statistics
        var implementedCount = requirementMap.Values.SelectMany(v => v).Count(t => !t.IsSkipped);
        var pendingCount = requirementMap.Values.SelectMany(v => v).Count(t => t.IsSkipped);
        
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine("| Metric | Count |");
        sb.AppendLine("|--------|-------|");
        sb.AppendLine($"| Total Test Methods | {totalTests} |");
        sb.AppendLine($"| Implemented Tests | {implementedCount} |");
        sb.AppendLine($"| Pending Tests | {pendingCount} |");
        sb.AppendLine($"| Requirements with Tests | {requirementMap.Count} |");
        sb.AppendLine();

        // Test coverage by type
        sb.AppendLine("## Test Coverage by Type");
        sb.AppendLine();
        var byType = requirementMap.Values
            .SelectMany(v => v)
            .GroupBy(t => t.TestType)
            .OrderBy(g => g.Key);
        
        sb.AppendLine("| Test Type | Count | Implemented | Pending |");
        sb.AppendLine("|-----------|-------|-------------|---------|");
        foreach (var group in byType)
        {
            var impl = group.Count(t => !t.IsSkipped);
            var pend = group.Count(t => t.IsSkipped);
            sb.AppendLine($"| {group.Key} | {group.Count()} | {impl} | {pend} |");
        }
        sb.AppendLine();

        // Detailed requirement-to-test mapping
        sb.AppendLine("## Requirement to Test Mapping");
        sb.AppendLine();

        foreach (var req in requirementMap.OrderBy(kvp => kvp.Key))
        {
            sb.AppendLine($"### {req.Key}");
            sb.AppendLine();
            
            var tests = req.Value.OrderBy(t => t.TestType).ThenBy(t => t.TestName);
            
            sb.AppendLine("| Test | Type | Category | Status | Description |");
            sb.AppendLine("|------|------|----------|--------|-------------|");
            
            foreach (var test in tests)
            {
                var status = test.IsSkipped ? "⏳ Pending" : "✅ Active";
                var desc = test.Description ?? "-";
                sb.AppendLine($"| `{test.TestName}` | {test.TestType} | {test.Category} | {status} | {desc} |");
            }
            
            sb.AppendLine();
        }

        // Requirements without tests (TODO: load from REQUIREMENTS.md)
        sb.AppendLine("## Requirements Analysis");
        sb.AppendLine();
        sb.AppendLine("### Known Requirements from REQUIREMENTS.md");
        sb.AppendLine();
        
        var allKnownRequirements = GetAllKnownRequirements();
        var unmappedRequirements = allKnownRequirements.Except(requirementMap.Keys).ToList();
        
        if (unmappedRequirements.Any())
        {
            sb.AppendLine("**⚠️ Requirements without tests:**");
            sb.AppendLine();
            foreach (var req in unmappedRequirements.OrderBy(r => r))
            {
                sb.AppendLine($"- {req}");
            }
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("✅ **All requirements have associated tests!**");
            sb.AppendLine();
        }

        // Test execution recommendations
        sb.AppendLine("## Test Execution Commands");
        sb.AppendLine();
        sb.AppendLine("```bash");
        sb.AppendLine("# Run all tests");
        sb.AppendLine("dotnet test");
        sb.AppendLine();
        sb.AppendLine("# Run only unit tests");
        sb.AppendLine("dotnet test --filter \"Category=Unit\"");
        sb.AppendLine();
        sb.AppendLine("# Run only integration tests");
        sb.AppendLine("dotnet test --filter \"Category=Integration\"");
        sb.AppendLine();
        sb.AppendLine("# Run tests for specific requirement");
        sb.AppendLine("dotnet test --filter \"RequirementId=FR-01\"");
        sb.AppendLine();
        sb.AppendLine("# Generate coverage report");
        sb.AppendLine("dotnet test --collect:\"XPlat Code Coverage\" --results-directory ./TestResults");
        sb.AppendLine("```");

        return sb.ToString();
    }

    private static List<string> GetAllKnownRequirements()
    {
        // This should ideally parse REQUIREMENTS.md
        // For now, return a comprehensive list based on our documentation
        return new List<string>
        {
            "FR-01", "FR-02", "FR-03", "FR-04", "FR-05", 
            "FR-06", "FR-07", "FR-08", "FR-09", "FR-10",
            "FR-11", "FR-12", "FR-13", "FR-14", "FR-15",
            "NFR-01", "NFR-02", "NFR-03", "NFR-04", "NFR-05", "NFR-06",
            "C-01", "C-02", "C-03"
        };
    }

    private class TestInfo
    {
        public string TestName { get; set; } = "";
        public string FullName { get; set; } = "";
        public TestType TestType { get; set; }
        public string Category { get; set; } = "";
        public string? Description { get; set; }
        public bool IsSkipped { get; set; }
    }
}
